package com.strider.datadefender.anonymizer.functions;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 *
 * @author Zaahid Bateson <zaahid.bateson@ubc.ca>
 */
public class LipsumTest {

    @Test
    public void testSentences() throws Exception {
        Lipsum test = new Lipsum();
        String sentences = test.sentences(3, 3);
        assertTrue(sentences.matches("([^\\.]+\\.){3}"));
    }

    @Test
    public void testParagraphs() throws Exception {
        Lipsum test = new Lipsum();
        String paragraphs = test.paragraphs(3);
        assertTrue(paragraphs.matches("^[^\r]+\r\n\r\n[^\r]+\r\n\r\n[^\r]+$"));
    }

    @Test
    public void testSimilar() throws Exception {
        Lipsum test = new Lipsum();

        String sentences = test.similar("This is a test.  It is excellent.  Should have a minimum of two sentences.");
        System.out.println("Testing for 3 sentences generated by similar text");
        assertTrue(sentences.matches("([^\\.]+\\.){2,}"));

        String paras = test.similar("This is also a test.\n\nIt is better.\n\nShould have three paragraphs.");
        System.out.println("Testing for 3 paragraphs generated by text with 3 paragraphs");
        assertTrue(paras.matches("^[^\r]+\r\n\r\n[^\r]+\r\n\r\n[^\r]+$"));
    }
}
